import java.io.IOException;
import java.io.PrintWriter;
import java.net.ServerSocket;
import java.net.Socket;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Main {
    public String getGreeting() {
        return "Hello world from Java!";
    }

    public static void main(String[] args) {
        System.out.println(new Main().getGreeting());
    }
}
